FROM python3

RUN mkdir /todo
COPY protobufs/ /service/protobufs/
COPY todo/ /service/todo/
WORKDIR /service/todo
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
RUN python3 -m grpc_tools.protoc -I ../protobufs --python_out=. \
           --grpc_python_out=. ../protobufs/todoservice.proto
RUN python3 -m pip install -r mysql_requirements.txt

EXPOSE 50051
ENTRYPOINT [ "python", "todoservice.py" ]