# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todoservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11todoservice.proto\x12\x0btodoservice\"\x1e\n\x0bTodoRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"G\n\x0cTodoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\t2R\n\x0bTodoService\x12\x43\n\x08GetTodos\x12\x18.todoservice.TodoRequest\x1a\x19.todoservice.TodoResponse\"\x00\x30\x01\x42\x32\n\x16io.dcs.one.todoserviceB\x10TodoServiceProtoP\x01\xa2\x02\x03TSPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todoservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026io.dcs.one.todoserviceB\020TodoServiceProtoP\001\242\002\003TSP'
  _TODOREQUEST._serialized_start=34
  _TODOREQUEST._serialized_end=64
  _TODORESPONSE._serialized_start=66
  _TODORESPONSE._serialized_end=137
  _TODOSERVICE._serialized_start=139
  _TODOSERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
