# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todoservice_pb2 as todoservice__pb2


class TodoServiceStub(object):
    """The todo service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTodos = channel.unary_stream(
                '/todoservice.TodoService/GetTodos',
                request_serializer=todoservice__pb2.TodoRequest.SerializeToString,
                response_deserializer=todoservice__pb2.TodoResponse.FromString,
                )


class TodoServiceServicer(object):
    """The todo service definition.
    """

    def GetTodos(self, request, context):
        """Sends a request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTodos': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTodos,
                    request_deserializer=todoservice__pb2.TodoRequest.FromString,
                    response_serializer=todoservice__pb2.TodoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todoservice.TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """The todo service definition.
    """

    @staticmethod
    def GetTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/todoservice.TodoService/GetTodos',
            todoservice__pb2.TodoRequest.SerializeToString,
            todoservice__pb2.TodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
